use_frameworks!

platform :ios, '8.0'

target 'ModularDemo_Example' do
  pod 'ModularDemo', :path => '../'

  target 'ModularDemo_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
