use_frameworks!

platform :ios, '8.0'
inhibit_all_warnings!
# 或者在pod的库后边添加 :inhibit_warnings => true

target 'ModularDemo_Example' do
  pod 'ModularDemo', :path => '../'

  target 'ModularDemo_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
